# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-24 12:39
from __future__ import unicode_literals

from django.db import migrations, models

import posts.models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_auto_20190723_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True,
                                    upload_to=posts.models.upload_location, width_field='width_field'),
        ),
    ]
