# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-26 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0004_auto_20190805_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
