# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-16 08:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0004_auto_20190805_0755'),
        ('comments', '0002_auto_20190816_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
            preserve_default=False,
        ),
    ]
