# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-16 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('comments', '0003_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
